Don't set public-read ACL
oshercc/coreos_installation_iso pull request #14
Opened 2020-08-10 20:04 UTC by carbonin

We don't have the permissions we need in prod to set this extra
ACL and we don't need it, so remove it.

2020-08-10 20:05 UTC, romfreiman approved these changes

2020-08-11 04:14 UTC, avishayt requested changes
Removing public read ACL is definitely good.  We need the object tag though - that's how our image expiration works (deleting images after 1 hour).

2020-08-11 15:21 UTC, avishayt approved these changes

2020-08-12 08:08 UTC, romfreiman commented
@yevgeny-shnaidman can u merge. just for the protocol :)

2020-08-12 08:24 UTC, merged